services:
  - type: web
    name: moticheck
    env: docker
    dockerfilePath: ./Dockerfile

    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: moticheck-db
          property: connectionString

    buildCommand: |
      bundle install &&
      bundle exec rails assets:precompile &&
      bundle exec rails db:prepare

    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT

databases:
  - name: moticheck-db
    databaseName: moticheck_production
    user: moticheckproduction
    user: your_app
